feat: adding new routes of crypto infos
tradersclub/TCStocksCrypto pull request #2
Opened 2021-08-31 07:59 UTC by luannevesbtc

## Checklist

- [:+1:  ] Eu rodei `make run` e a aplicação rodou sem erros.
- [ :+1: ] Eu rodei `make test` e os testes rodaram sem erros.

## O que foi feito?

Foi adicionado os eventos para as três primeiras rotas de informações de crypto seguindo a task abaixo

## Jira Issue Number:

https://tradersclub.atlassian.net/browse/DS-100?focusedCommentId=29716&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-29716
## Outras informações

N/A

2021-08-31 12:08 UTC, rafaelmftc reviewed
Recomendo criar mocks das respostas esperadas, uma forma de selecionar um mock_mode=true e testes de integração que verifiquem as chamadas via nats e seus resultados mockados, o que acha?

2021-08-31 12:23 UTC, luannevesbtc commented
> Recomendo criar mocks das respostas esperadas, uma forma de selecionar um mock_mode=true e testes de integração que verifiquem as chamadas via nats e seus resultados mockados, o que acha?

Faz sentido demais, vou fazer aqui e subo mais um commit com os tests ok?

2021-09-13 13:52 UTC, diegosantos-tc commented on api/api.go
> +	health "github.com/tradersclub/TCStocksCrypto/api/health"
pode remover esses códigos de health, isso é só de exemplo do template

2021-09-13 13:54 UTC, diegosantos-tc commented on event/crypto/crypto.go
> +const (
O ideal é que esses canais fiquem no TCNatsModel

2021-09-13 13:55 UTC, diegosantos-tc commented on event/crypto/crypto.go
> +type getGlobalInfos struct {
as structs do nats tbm é melhor colocar no TCNatsModel, isso ajuda na organização

2021-09-13 13:56 UTC, diegosantos-tc commented on event/crypto/crypto.go
> +		getGlobalInfosResponse.Data = infos
esse método precisa mandar um response pra quem fizer o request? Se sim, está faltando o PublishRequest

2021-09-13 13:58 UTC, diegosantos-tc commented on event/crypto/crypto.go
> +		getCryptoCategoriesResponse.Data = categories
esse método precisa mandar um response pra quem fizer o request? Se sim, está faltando o PublishRequest

2021-09-13 13:59 UTC, diegosantos-tc commented on event/crypto/crypto.go
> +		getCryptoTickersResponse.Data = list
esse método precisa mandar um response pra quem fizer o request? Se sim, está faltando o PublishRequest

2021-09-13 14:01 UTC, diegosantos-tc requested changes
alguns detalhes no Nats

2021-09-13 14:35 UTC, otherpirate requested changes

2021-09-13 14:35 UTC, otherpirate commented on app/crypto/crypto.go
> +		return nil, tcerr.NewError(http.StatusInternalServerError, "erro ao realizar o get das infos globais", nil)
a descrição do erro não ta correta com o erro

2021-09-13 14:35 UTC, otherpirate commented on app/crypto/crypto.go
> +		return nil, tcerr.NewError(http.StatusInternalServerError, "erro ao realizar o get das categorias de crypto", nil)
aqui também

2021-09-13 14:35 UTC, otherpirate commented on app/crypto/crypto.go
> +		return nil, tcerr.NewError(http.StatusInternalServerError, "erro ao realizar o get das cryptos", nil)
aqui também

2021-09-13 14:35 UTC, otherpirate commented on app/crypto/crypto_test.go
> +	for name, cs := range cases {
:star_struck:

2021-09-13 14:55 UTC, luannevesbtc commented on event/crypto/crypto.go
> +		getGlobalInfosResponse.Data = infos
Não, o retorno dele é publicar em outro tópico do nats

2021-09-13 14:56 UTC, luannevesbtc commented on event/crypto/crypto.go
> +		getCryptoTickersResponse.Data = list
Não, o retorno dele é publicar em outro tópico do nats

2021-09-13 14:56 UTC, luannevesbtc commented on event/crypto/crypto.go
> +		getCryptoCategoriesResponse.Data = categories
Não, o retorno dele é publicar em outro tópico do nats

2021-09-13 17:46 UTC, luannevesbtc commented on api/api.go
> +	health "github.com/tradersclub/TCStocksCrypto/api/health"
FIxed :+1:

2021-09-13 17:47 UTC, luannevesbtc commented on event/crypto/crypto.go
> +const (
FIxed :+1:

2021-09-13 17:47 UTC, luannevesbtc commented on event/crypto/crypto.go
> +type getGlobalInfos struct {
FIxed :+1:

2021-09-13 17:47 UTC, luannevesbtc commented on app/crypto/crypto.go
> +		return nil, tcerr.NewError(http.StatusInternalServerError, "erro ao realizar o get das infos globais", nil)
Fixed :+1:

2021-09-13 17:47 UTC, luannevesbtc commented on app/crypto/crypto.go
> +		return nil, tcerr.NewError(http.StatusInternalServerError, "erro ao realizar o get das categorias de crypto", nil)
Fixed :+1:

2021-09-13 17:47 UTC, luannevesbtc commented on app/crypto/crypto.go
> +		return nil, tcerr.NewError(http.StatusInternalServerError, "erro ao realizar o get das cryptos", nil)
Fixed :+1:

2021-09-13 17:53 UTC, mauro-murari-tc approved these changes

2021-09-13 18:03 UTC, diegosantos-tc approved these changes

2021-09-13 18:06 UTC, merged